Hour Dataset

In [4]:
import pandas as pd

In [5]:
hour=pd.read_csv(r'C:\Users\kARPOORAPU VANIPRIYA\Downloads\hour.csv.zip')

In [6]:
hour

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

In [7]:
hour.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  object
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   workingday  17379 non-null  int64
 9   weathersit  17379 non-null  int64
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64
 15  registered  17379 non-null  int64
 16  cnt         17379 non-null  int64
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB

In [8]:
hour.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [9]:
hour.duplicated().sum()

0

In [10]:
hour.dropna()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

In [11]:
hour['dteday']=pd.to_datetime(hour['dteday'])

In [12]:
hour.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  datetime64[ns]
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   workingday  17379 non-null  int64
 9   weathersit  17379 non-null  int64
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64
 15  registered  17379 non-null  int64
 16  cnt         17379 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(12)
memory usage: 2.3 MB

Day Dataset

In [13]:
day=pd.read_csv(r"C:\Users\kARPOORAPU VANIPRIYA\Downloads\day.csv.zip")

In [14]:
day

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,727,2012-12-27,1,1,12,0,4,1,2,0.254167,0.226642,0.652917,0.350133,247,1867,2114
727,728,2012-12-28,1,1,12,0,5,1,2,0.253333,0.255046,0.590000,0.155471,644,2451,3095
728,729,2012-12-29,1,1,12,0,6,0,2,0.253333,0.242400,0.752917,0.124383,159,1182,1341
729,730,2012-12-30,1,1,12,0,0,0,1,0.255833,0.231700,0.483333,0.350754,364,1432,1796
730,731,2012-12-31,1,1,12,0,1,1,2,0.215833,0.223487,0.577500,0.154846,439,2290,2729

In [15]:
day.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [16]:
day.duplicated().sum()

0

In [17]:
day.dropna()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,727,2012-12-27,1,1,12,0,4,1,2,0.254167,0.226642,0.652917,0.350133,247,1867,2114
727,728,2012-12-28,1,1,12,0,5,1,2,0.253333,0.255046,0.590000,0.155471,644,2451,3095
728,729,2012-12-29,1,1,12,0,6,0,2,0.253333,0.242400,0.752917,0.124383,159,1182,1341
729,730,2012-12-30,1,1,12,0,0,0,1,0.255833,0.231700,0.483333,0.350754,364,1432,1796
730,731,2012-12-31,1,1,12,0,1,1,2,0.215833,0.223487,0.577500,0.154846,439,2290,2729

In [18]:
day['dteday']=pd.to_datetime(day['dteday'])

In [19]:
day.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     731 non-null    int64
 1   dteday      731 non-null    datetime64[ns]
 2   season      731 non-null    int64
 3   yr          731 non-null    int64
 4   mnth        731 non-null    int64
 5   holiday     731 non-null    int64
 6   weekday     731 non-null    int64
 7   workingday  731 non-null    int64
 8   weathersit  731 non-null    int64
 9   temp        731 non-null    float64
 10  atemp       731 non-null    float64
 11  hum         731 non-null    float64
 12  windspeed   731 non-null    float64
 13  casual      731 non-null    int64
 14  registered  731 non-null    int64
 15  cnt         731 non-null    int64
dtypes: datetime64[ns](1), float64(4), int64(11)
memory usage: 91.5 KB

In [20]:
cols_to_drop = ['instant', 'dteday', 'yr', 'casual', 'registered']

hour = hour.drop(columns=cols_to_drop, errors='ignore')

day = day.drop(columns=cols_to_drop, errors='ignore')

In [21]:
hour.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   season      17379 non-null  int64
 1   mnth        17379 non-null  int64
 2   hr          17379 non-null  int64
 3   holiday     17379 non-null  int64
 4   weekday     17379 non-null  int64
 5   workingday  17379 non-null  int64
 6   weathersit  17379 non-null  int64
 7   temp        17379 non-null  float64
 8   atemp       17379 non-null  float64
 9   hum         17379 non-null  float64
 10  windspeed   17379 non-null  float64
 11  cnt         17379 non-null  int64
dtypes: float64(4), int64(8)
memory usage: 1.6 MB

In [22]:
day.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   season      731 non-null    int64
 1   mnth        731 non-null    int64
 2   holiday     731 non-null    int64
 3   weekday     731 non-null    int64
 4   workingday  731 non-null    int64
 5   weathersit  731 non-null    int64
 6   temp        731 non-null    float64
 7   atemp       731 non-null    float64
 8   hum         731 non-null    float64
 9   windspeed   731 non-null    float64
 10  cnt         731 non-null    int64
dtypes: float64(4), int64(7)
memory usage: 62.9 KB

Removing Outliers

In [23]:
def remove_outliers_iqr(df):
    numeric_cols = df.select_dtypes(include='number').columns
    Q1 = df[numeric_cols].quantile(0.25)
    Q3 = df[numeric_cols].quantile(0.75)
    IQR = Q3 - Q1

    df_clean = df[~(
        (df[numeric_cols] < (Q1 - 1.5 * IQR)) |
        (df[numeric_cols] > (Q3 + 1.5 * IQR))
    ).any(axis=1)]
    
    return df_clean

In [24]:
hour_clean = remove_outliers_iqr(hour)
day_clean = remove_outliers_iqr(day)

print("Hour original:", hour.shape, " → After outlier removal:", hour_clean.shape)
print("Day original:", day.shape, " → After outlier removal:", day_clean.shape)

Hour original: (17379, 12)  → After outlier removal: (16029, 12)
Day original: (731, 11)  → After outlier removal: (696, 11)

Model Training

In [ ]:

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [28]:
X = hour.drop('cnt', axis=1)
y = hour['cnt']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [29]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [30]:

lr = LinearRegression()
lr.fit(X_train_scaled, y_train)

train_pred_lr = lr.predict(X_train_scaled)
test_pred_lr = lr.predict(X_test_scaled)

print("Linear Regression")
print("Train R2:", r2_score(y_train, train_pred_lr))
print("Test R2 :", r2_score(y_test, test_pred_lr))

Linear Regression
Train R2: 0.33774864801058435
Test R2 : 0.3455468386885291

In [31]:

dt = DecisionTreeRegressor(max_depth=10, random_state=42)
dt.fit(X_train, y_train)

train_pred_dt = dt.predict(X_train)
test_pred_dt = dt.predict(X_test)

print("\nDecision Tree")
print("Train R2:", r2_score(y_train, train_pred_dt))
print("Test R2 :", r2_score(y_test, test_pred_dt))

Decision Tree
Train R2: 0.8539092953816037
Test R2 : 0.8087746120801294

In [32]:
rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=15,
    random_state=42
)

rf.fit(X_train, y_train)

train_pred_rf = rf.predict(X_train)
test_pred_rf = rf.predict(X_test)

print("\nRandom Forest")
print("Train R2:", r2_score(y_train, train_pred_rf))
print("Test R2 :", r2_score(y_test, test_pred_rf))

Random Forest
Train R2: 0.9549977075453349
Test R2 : 0.8635466284949065

Hyper Parameter Tuninig on Hour Dataset

In [35]:

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

In [ ]:
def train_evaluate(grid, X_train, X_test, y_train, y_test):
    best_model = grid.best_estimator_

    y_train_pred = best_model.predict(X_train)
    y_test_pred = best_model.predict(X_test)

    train_r2 = r2_score(y_train, y_train_pred)
    test_r2 = r2_score(y_test, y_test_pred)

    return train_r2, test_r2

In [37]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=42)

param_grid_dt = {
    'max_depth': [5, 10, 15, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

dt_grid = GridSearchCV(
    dt, param_grid_dt, cv=5, scoring='r2', n_jobs=-1
)

dt_grid.fit(X_train, y_train)

dt_train_r2, dt_test_r2 = train_evaluate(
    dt_grid, X_train, X_test, y_train, y_test
)

print("\nDecision Tree")
print("Best Params:", dt_grid.best_params_)
print("Train R2:", dt_train_r2)
print("Test R2 :", dt_test_r2)

Decision Tree
Best Params: {'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 2}
Train R2: 0.8498393919697573
Test R2 : 0.8135523410341616

In [39]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state=42)

param_grid_rf = {
    'n_estimators': [100, 200],
    'max_depth': [10, 15, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

rf_grid = GridSearchCV(
    rf, param_grid_rf, cv=5, scoring='r2', n_jobs=-1
)

rf_grid.fit(X_train, y_train)

rf_train_r2, rf_test_r2 = train_evaluate(
    rf_grid, X_train, X_test, y_train, y_test
)

print("\nRandom Forest")
print("Best Params:", rf_grid.best_params_)
print("Train R2:", rf_train_r2)
print("Test R2 :", rf_test_r2)

Random Forest
Best Params: {'max_depth': 20, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
Train R2: 0.9787222337854992
Test R2 : 0.8661645322069691

Day Dataset -Model Training

In [41]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [42]:
lr = LinearRegression()
lr.fit(X_train_scaled, y_train)

train_pred_lr = lr.predict(X_train_scaled)
test_pred_lr = lr.predict(X_test_scaled)

print("Linear Regression")
print("Train R2:", r2_score(y_train, train_pred_lr))
print("Test R2 :", r2_score(y_test, test_pred_lr))

Linear Regression
Train R2: 0.33774864801058435
Test R2 : 0.3455468386885291

In [43]:
dt = DecisionTreeRegressor(max_depth=10, random_state=42)
dt.fit(X_train, y_train)

train_pred_dt = dt.predict(X_train)
test_pred_dt = dt.predict(X_test)

print("\nDecision Tree")
print("Train R2:", r2_score(y_train, train_pred_dt))
print("Test R2 :", r2_score(y_test, test_pred_dt))

Decision Tree
Train R2: 0.8539092953816037
Test R2 : 0.8087746120801294

In [44]:
rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=15,
    random_state=42
)

rf.fit(X_train, y_train)

train_pred_rf = rf.predict(X_train)
test_pred_rf = rf.predict(X_test)

print("\nRandom Forest")
print("Train R2:", r2_score(y_train, train_pred_rf))
print("Test R2 :", r2_score(y_test, test_pred_rf))

Random Forest
Train R2: 0.9549977075453349
Test R2 : 0.8635466284949065

Hyper Parameter tuning

In [46]:
def evaluate_model(grid, X_train, X_test, y_train, y_test):
    model = grid.best_estimator_

    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    train_r2 = r2_score(y_train, train_pred)
    test_r2 = r2_score(y_test, test_pred)

    return train_r2, test_r2

In [47]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=42)

param_grid_dt = {
    'max_depth': [5, 10, 15, 20, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

dt_grid = GridSearchCV(
    dt, param_grid_dt, cv=5, scoring='r2', n_jobs=-1
)

dt_grid.fit(X_train, y_train)

dt_train_r2, dt_test_r2 = evaluate_model(
    dt_grid, X_train, X_test, y_train, y_test
)

print("\nDecision Tree")
print("Best Params:", dt_grid.best_params_)
print("Train R2:", dt_train_r2)
print("Test R2 :", dt_test_r2)

Decision Tree
Best Params: {'max_depth': 10, 'min_samples_leaf': 4, 'min_samples_split': 2}
Train R2: 0.8498393919697573
Test R2 : 0.8135523410341616

In [48]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state=42)

param_grid_rf = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 15, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

rf_grid = GridSearchCV(
    rf, param_grid_rf, cv=5, scoring='r2', n_jobs=-1
)

rf_grid.fit(X_train, y_train)

rf_train_r2, rf_test_r2 = evaluate_model(
    rf_grid, X_train, X_test, y_train, y_test
)

print("\nRandom Forest")
print("Best Params:", rf_grid.best_params_)
print("Train R2:", rf_train_r2)
print("Test R2 :", rf_test_r2)

Random Forest
Best Params: {'max_depth': 20, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 300}
Train R2: 0.9788388432734157
Test R2 : 0.8667333801704846