In [1]:
import pandas as pd

In [2]:
hour=pd.read_csv(r'C:\Users\kARPOORAPU VANIPRIYA\Downloads\hour.csv.zip')

In [3]:
hour

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

In [4]:
day=pd.read_csv(r"C:\Users\kARPOORAPU VANIPRIYA\Downloads\day.csv.zip")

In [5]:
day

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,727,2012-12-27,1,1,12,0,4,1,2,0.254167,0.226642,0.652917,0.350133,247,1867,2114
727,728,2012-12-28,1,1,12,0,5,1,2,0.253333,0.255046,0.590000,0.155471,644,2451,3095
728,729,2012-12-29,1,1,12,0,6,0,2,0.253333,0.242400,0.752917,0.124383,159,1182,1341
729,730,2012-12-30,1,1,12,0,0,0,1,0.255833,0.231700,0.483333,0.350754,364,1432,1796
730,731,2012-12-31,1,1,12,0,1,1,2,0.215833,0.223487,0.577500,0.154846,439,2290,2729

In [18]:
hour['dteday']=pd.to_datetime(hour['dteday'])

In [19]:
day['dteday']=pd.to_datetime(day['dteday'])

In [20]:
hour.info()
day.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   dteday      17379 non-null  datetime64[ns]
 1   season      17379 non-null  int64
 2   mnth        17379 non-null  int64
 3   hr          17379 non-null  int64
 4   holiday     17379 non-null  int64
 5   weekday     17379 non-null  int64
 6   workingday  17379 non-null  int64
 7   weathersit  17379 non-null  int64
 8   temp        17379 non-null  float64
 9   atemp       17379 non-null  float64
 10  hum         17379 non-null  float64
 11  windspeed   17379 non-null  float64
 12  cnt         17379 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(8)
memory usage: 1.7 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   dteday      731 non-null    datetime64[ns]
 1   season      731 non-null    int64
 2   mnth        731 non-null    int64
 3   holiday     731 non-null    int64
 4   weekday     731 non-null    int64
 5   workingday  731 non-null    int64
 6   weathersit  731 non-null    int64
 7   temp        731 non-null    float64
 8   atemp       731 non-null    float64
 9   hum         731 non-null    float64
 10  windspeed   731 non-null    float64
 11  cnt         731 non-null    int64
dtypes: datetime64[ns](1), float64(4), int64(7)
memory usage: 68.7 KB

In [26]:
cols_to_drop = ['instant', 'dteday', 'yr', 'casual', 'registered']

hour = hour.drop(columns=cols_to_drop, errors='ignore')

day = day.drop(columns=cols_to_drop, errors='ignore')

In [27]:
hour.info()
day.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   season      17379 non-null  int64
 1   mnth        17379 non-null  int64
 2   hr          17379 non-null  int64
 3   holiday     17379 non-null  int64
 4   weekday     17379 non-null  int64
 5   workingday  17379 non-null  int64
 6   weathersit  17379 non-null  int64
 7   temp        17379 non-null  float64
 8   atemp       17379 non-null  float64
 9   hum         17379 non-null  float64
 10  windspeed   17379 non-null  float64
 11  cnt         17379 non-null  int64
dtypes: float64(4), int64(8)
memory usage: 1.6 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   season      731 non-null    int64
 1   mnth        731 non-null    int64
 2   holiday     731 non-null    int64
 3   weekday     731 non-null    int64
 4   workingday  731 non-null    int64
 5   weathersit  731 non-null    int64
 6   temp        731 non-null    float64
 7   atemp       731 non-null    float64
 8   hum         731 non-null    float64
 9   windspeed   731 non-null    float64
 10  cnt         731 non-null    int64
dtypes: float64(4), int64(7)
memory usage: 62.9 KB

In [28]:
def remove_outliers_iqr(df):
    numeric_cols = df.select_dtypes(include='number').columns
    Q1 = df[numeric_cols].quantile(0.25)
    Q3 = df[numeric_cols].quantile(0.75)
    IQR = Q3 - Q1

    df_clean = df[~(
        (df[numeric_cols] < (Q1 - 1.5 * IQR)) |
        (df[numeric_cols] > (Q3 + 1.5 * IQR))
    ).any(axis=1)]
    
    return df_clean

In [29]:
hour_clean = remove_outliers_iqr(hour)
day_clean = remove_outliers_iqr(day)

print("Hour original:", hour.shape, " → After outlier removal:", hour_clean.shape)
print("Day original:", day.shape, " → After outlier removal:", day_clean.shape)

Hour original: (17379, 12)  → After outlier removal: (16029, 12)
Day original: (731, 11)  → After outlier removal: (696, 11)

Model Training

In [30]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

In [31]:
# Hour dataset
X_hour = hour.drop('cnt', axis=1)
y_hour = hour['cnt']

# Day dataset
X_day = day.drop('cnt', axis=1)
y_day = day['cnt']

In [32]:
Xh_train, Xh_test, yh_train, yh_test = train_test_split(
    X_hour, y_hour, test_size=0.2, random_state=42
)

Xd_train, Xd_test, yd_train, yd_test = train_test_split(
    X_day, y_day, test_size=0.2, random_state=42
)

In [33]:
scaler = StandardScaler()

# Hour
Xh_train_scaled = scaler.fit_transform(Xh_train)
Xh_test_scaled = scaler.transform(Xh_test)

# Day
Xd_train_scaled = scaler.fit_transform(Xd_train)
Xd_test_scaled = scaler.transform(Xd_test)

In [34]:
def evaluate_model(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, pred)
    rmse = np.sqrt(mean_squared_error(y_test, pred))
    r2 = r2_score(y_test, pred)

    return mae, rmse, r2

In [35]:
lr = LinearRegression()
rf = RandomForestRegressor(random_state=42)
gb = GradientBoostingRegressor(random_state=42)
models = [lr, rf, gb]
model_names = ["Linear Regression", "Random Forest", "Gradient Boosting"]

In [36]:
print("📌 HOUR DATASET MODEL PERFORMANCE\n")
for name, model in zip(model_names, models):
    mae, rmse, r2 = evaluate_model(model, Xh_train_scaled, Xh_test_scaled, yh_train, yh_test)
    print(f"{name}: MAE={mae:.2f}, RMSE={rmse:.2f}, R2={r2:.3f}")

📌 HOUR DATASET MODEL PERFORMANCE

Linear Regression: MAE=106.75, RMSE=143.96, R2=0.346
Random Forest: MAE=42.19, RMSE=65.15, R2=0.866
Gradient Boosting: MAE=56.35, RMSE=82.44, R2=0.785

In [37]:
print("\n📌 DAY DATASET MODEL PERFORMANCE\n")
for name, model in zip(model_names, models):
    mae, rmse, r2 = evaluate_model(model, Xd_train_scaled, Xd_test_scaled, yd_train, yd_test)
    print(f"{name}: MAE={mae:.2f}, RMSE={rmse:.2f}, R2={r2:.3f}")

📌 DAY DATASET MODEL PERFORMANCE

Linear Regression: MAE=1143.39, RMSE=1340.51, R2=0.552
Random Forest: MAE=1083.29, RMSE=1303.59, R2=0.576
Gradient Boosting: MAE=1066.79, RMSE=1244.58, R2=0.614